# Generated by Django 4.2.3 on 2023-08-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('altura', models.FloatField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posicion', models.CharField(max_length=50)),
                ('puntos_por_partido', models.DecimalField(decimal_places=1, max_digits=4)),
                ('asistencias_por_partido', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rebotes_por_partido', models.DecimalField(decimal_places=1, max_digits=4)),
                ('edad', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.liga'),
        ),
    ]
